indexPriceConfig = {
    'btc/susd': [
        # ['huobiSpot', 'binanceSpot', 'okexSpot', 'poloSpot'],
        ['huobiSpot', 'binanceSpot', 'poloSpot'],
        [0.55, 0.35, 0.1],
        0.01,
    ],
    'btc/usdt': [
        # ['huobiSpot', 'binanceSpot', 'okexSpot', 'poloSpot'],
        ['huobiSpot', 'binanceSpot', 'poloSpot'],
        [0.55, 0.35, 0.1],
        0.01,
    ],
    'eth/usdt': [
        # ['huobiSpot', 'binanceSpot', 'okexSpot', 'poloSpot'],
        ['huobiSpot', 'binanceSpot', 'okexSpot'],
        [0.55, 0.35, 0.1],
        0.01,
    ],
    'eos/usdt': [
        # ['huobiSpot', 'binanceSpot', 'okexSpot', 'hitbtcSpot'],
        ['huobiSpot', 'binanceSpot', 'hitbtcSpot'],
        [0.6, 0.2, 0.2],
        0.01,
    ],

    'comp/usdt': [
        # ['mxcSpot', 'binanceSpot', 'okexSpot', 'hitbtcSpot'],
        ['mxcSpot', 'binanceSpot', 'hitbtcSpot'],
        [0.5, 0.45, 0.05],
        0.05,
    ],
    'atom/usdt': [
        # ['huobiSpot', 'binanceSpot', 'okexSpot', 'poloSpot'],
        ['huobiSpot', 'binanceSpot',  'poloSpot'],
        [0.45, 0.5, 0.05],
        0.02,
    ],
    'xrp/usdt': [
        ['huobiSpot', 'binanceSpot', 'mxcSpot'],
        [0.55, 0.35, 0.1],
        0.01,
    ],
    'ltc/usdt': [
        # ['huobiSpot', 'binanceSpot', 'okexSpot', 'hitbtcSpot'],
        ['huobiSpot', 'binanceSpot', 'hitbtcSpot'],
        [0.6, 0.2, 0.2],
        0.01,
    ],
    'bch/usdt': [
        # ['huobiSpot', 'binanceSpot', 'okexSpot', 'hitbtcSpot'],
        ['huobiSpot', 'binanceSpot', 'hitbtcSpot'],
        # ['binanceSpot'],
        [0.6, 0.25, 0.15],
        0.01,
    ],
    'bsv/usdt': [
        # ['huobiSpot', 'okexSpot', 'hitbtcSpot'],
        ['huobiSpot', 'hitbtcSpot'],
        [0.7, 0.2],
        0.01,
    ],
    'etc/usdt': [
        ['huobiSpot', 'binanceSpot', 'hitbtcSpot'],
        [0.5, 0.25, 0.25],
        0.01,
    ],
    'trx/usdt': [
        ['huobiSpot', 'binanceSpot', 'hitbtcSpot'],
        [0.4, 0.4, 0.2],
        0.01,
    ],
    'dot/usdt': [
        ['huobiSpot', 'binanceSpot', 'hitbtcSpot'],
        [0.4, 0.4, 0.2],
        0.01,
    ],
    'link/usdt': [
        ['huobiSpot', 'binanceSpot'],
        [0.5, 0.4],
        0.01,
    ],
    'ada/usdt': [
        ['huobiSpot', 'binanceSpot', 'hitbtcSpot'],
        [0.35, 0.4, 0.25],
        0.01,
    ],
    'mkr/usdt': [
        ['huobiSpot', 'binanceSpot', 'kucoinSpot'],
        [0.35, 0.5, 0.15],
        0.05,
    ],
    'sushi/usdt': [
        ['huobiSpot', 'binanceSpot', 'gateioSpot'],
        [0.5, 0.3, 0.2],
        0.01,
    ],
    'uni/usdt': [
        ['huobiSpot', 'binanceSpot', 'gateioSpot'],
        [0.35, 0.4, 0.25],
        0.02,
    ],
    'fil/usdt': [
        ['huobiSpot', 'binanceSpot', 'gateioSpot'],
        [0.65, 0.3, 0.05],
        0.02,
    ],
    'grt/usdt': [
        ['huobiSpot', 'binanceSpot', 'gateioSpot', 'okexSpot'],
        [0.1, 0.6, 0.05, 0.25],
        0.02,
    ],
    '1inch/usdt': [
        ['huobiSpot', 'binanceSpot', 'gateioSpot', 'okexSpot'],
        [0.1, 0.6, 0.05, 0.25],
        0.02,
    ],
    'dash/usdt': [
        ['huobiSpot', 'binanceSpot', 'hitbtcSpot', 'okexSpot'],
        [0.25, 0.4, 0.1, 0.25],
        0.01,
    ],
    'dot/usdt': [
        ['huobiSpot', 'binanceSpot', 'bitfinexSpot', 'okexSpot'],
        [0.25, 0.4, 0.1, 0.25],
        0.01,
    ],
    'aave/usdt': [
        ['huobiSpot', 'binanceSpot', 'okexSpot'],
        [0.25, 0.5, 0.25],
        0.01,
    ],
    'yfi/usdt': [
        ['huobiSpot', 'binanceSpot', 'okexSpot'],
        [0.3, 0.5, 0.2],
        0.01,
    ],
    'doge/usdt': [
        ['huobiSpot', 'binanceSpot', 'okexSpot'],
        [0.4, 0.3, 0.3],
        0.01,
    ],
    'xmr/usdt': [
        ['huobiSpot', 'binanceSpot', 'okexSpot'],
        [0.3, 0.4, 0.3],
        0.01,
    ],
    'avax/usdt': [
        ['huobiSpot', 'binanceSpot', 'okexSpot'],
        [0.2, 0.5, 0.3],
        0.01,
    ],
    'snx/usdt': [
        ['huobiSpot', 'binanceSpot', 'okexSpot'],
        [0.2, 0.5, 0.3],
        0.01,
    ],
    'ksm/usdt': [
        ['huobiSpot', 'binanceSpot', 'okexSpot'],
        [0.2, 0.5, 0.3],
        0.01,
    ],
    'zec/usdt': [
        ['huobiSpot', 'binanceSpot', 'okexSpot'],
        [0.5, 0.3, 0.2],
        0.01,
    ],
    'zil/usdt': [
        ['huobiSpot', 'binanceSpot', 'okexSpot'],
        [0.2, 0.5, 0.3],
        0.01,
    ],
    'waves/usdt': [
        ['huobiSpot', 'binanceSpot', 'okexSpot'],
        [0.2, 0.5, 0.3],
        0.01,
    ],
    'zen/usdt': [
        ['huobiSpot', 'binanceSpot', 'okexSpot'],
        [0.4, 0.4, 0.2],
        0.01,
    ],
    'ont/usdt': [
        ['huobiSpot', 'binanceSpot', 'okexSpot'],
        [0.2, 0.5, 0.3],
        0.01,
    ],

    'bnb+ht/usdt': [
        {'bnb/usdt': ['binanceUsdtSwap', 'gateioUsdtSwap'], 'ht/usdt': ['huobiSpot', 'gateioUsdtSwap']},
        {'bnb/usdt': [0.9, 0.05], 'ht/usdt': [0.9, 0.05]},
        0.02,
    ],
    'bnb-ht/usdt': [
        {'bnb/usdt': ['binanceUsdtSwap', 'gateioUsdtSwap'], 'ht/usdt': ['huobiSpot', 'gateioUsdtSwap']},
        {'bnb/usdt': [0.9, 0.05], 'ht/usdt': [0.9, 0.05]},
        0.02,
    ],

    'gray/usdt': {
        'btc/usdt': [['binanceSpot', 'huobiSpot'], 0.79, 33518.95],
        'eth/usdt': [['binanceSpot', 'huobiSpot'], 0.15, 1340.59],
        'etc/usdt': [['binanceSpot', 'huobiSpot'], 0.01, 7.3699],
        'bch/usdt': [['binanceSpot', 'huobiSpot'], 0.01, 398.73],
        'ltc/usdt': [['binanceSpot', 'huobiSpot'], 0.01, 130.23],
        'zec/usdt': [['binanceSpot', 'huobiSpot'], 0.01, 83.79],
        'zen/usdt': [['binanceSpot', 'huobiSpot'], 0.01, 33.503],
        'xlm/usdt': [['binanceSpot', 'huobiSpot'], 0.01, 0.2891],       
    },
    'pregray/usdt': {
        'aave/usdt': [['binanceSpot', 'huobiSpot'], 0.0833, 287.601],
        'ada/usdt': [['binanceSpot', 'huobiSpot'], 0.0833, 0.3406],
        'atom/usdt': [['binanceSpot', 'huobiSpot'], 0.0833, 7.85],
        'eos/usdt': [['binanceSpot', 'huobiSpot'], 0.0833, 2.7106],
        'xmr/usdt': [['binanceSpot', 'huobiSpot'], 0.0833, 137.94],
        'dot/usdt': [['binanceSpot', 'huobiSpot'], 0.0833, 16.4371],
        'bat/usdt': [['binanceSpot', 'huobiSpot'], 0.0833, 0.2998],
        'link/usdt': [['binanceSpot', 'huobiSpot'], 0.0833, 22.579],       
        'mana/usdt': [['binanceSpot', 'huobiSpot'], 0.0833, 0.1533],       
        'fil/usdt': [['binanceSpot', 'huobiSpot'], 0.0833, 22.1519],       
        'lpt/usdt': [['mxcSpot'], 0.0833, 3.201],       
        'xtz/usdt': [['binanceSpot', 'huobiSpot'], 0.0833, 2.8607],       
    },
    'polka/usdt': {
        'dot/usdt': [['binanceSpot', 'huobiSpot'], 0.2, 16.4371],
        'ksm/usdt': [['binanceSpot', 'huobiSpot'], 0.3, 104.778],
        'ocean/usdt': [['binanceSpot'], 0.05, 0.554],
        'pols/usdt': [['huobiSpot'], 0.05, 1.0774],
        'akro/usdt': [['binanceSpot', 'huobiSpot'], 0.05, 0.0182],
        'mxc/usdt': [['huobiSpot'], 0.05, 0.01307],
        'pha/usdt': [['huobiSpot'], 0.05, 0.273],
        'ankr/usdt': [['binanceSpot', 'huobiSpot'], 0.05, 0.0117],       
        'celr/usdt': [['binanceSpot', 'huobiSpot'], 0.05, 0.0088],       
        'dock/usdt': [['binanceSpot', 'huobiSpot'], 0.05, 0.0227],       
        'cru/usdt': [['huobiSpot'], 0.05, 7.2653],       
        'ring/usdt': [['huobiSpot'], 0.05, 0.0789],       
    },
    'defi/usdt': {
        'uni/usdt': [['binanceSpot', 'huobiSpot'], 0.2, 15.2335],
        'aave/usdt': [['binanceSpot', 'huobiSpot'], 0.1, 287.601],
        'snx/usdt': [['binanceSpot', 'huobiSpot'], 0.1, 16.628],
        'mkr/usdt': [['binanceSpot', 'huobiSpot'], 0.1, 1421.91],
        'sushi/usdt': [['binanceSpot', 'huobiSpot'], 0.1, 9.132],
        'yfi/usdt': [['binanceSpot', 'huobiSpot'], 0.1, 29038.96],
        '1inch/usdt': [['binanceSpot', 'huobiSpot'], 0.1, 3.4971],
        'comp/usdt': [['binanceSpot', 'huobiSpot'], 0.2, 301.25],       
    },
    'nft/usdt': {
        'enj/usdt': [['binanceSpot'], 0.1, 0.343],
        'mana/usdt': [['binanceSpot', 'huobiSpot'], 0.2, 0.1533],
        'sand/usdt': [['binanceSpot', 'huobiSpot'], 0.2, 0.0873],
        'waxp/usdt': [['huobiSpot'], 0.1, 0.0404],
        'cocos/usdt': [['binanceSpot'], 0.1, 0.4784],
        'meme/usdt': [['okexSpot'], 0.2, 519.7],
        'ghst/usdt': [['mxcSpot'], 0.1, 0.6603],
    },
    'heco/usdt': {
        'bags/usdt': [['huobiSpot'], 0.5, 335.6269],
        'mdx/usdt': [['huobiSpot'], 0.5, 2.702],
    },
    'layer2/usdt': {
        'snx/usdt': [['binanceSpot', 'huobiSpot'], 0.2, 16.628],
        'lrc/usdt': [['binanceSpot', 'huobiSpot'], 0.2, 0.4441],
        'near/usdt': [['binanceSpot', 'huobiSpot'], 0.2, 2.0851],
        'omg/usdt': [['binanceSpot', 'huobiSpot'], 0.1, 3.4399],
        'celr/usdt': [['binanceSpot', 'huobiSpot'], 0.2, 0.0088],
        'fun/usdt': [['binanceSpot'], 0.1, 0.0313],
    },

    'btc/usd': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.25, 0.25, 0.25, 0.25],
        0.01,
    ],
    'eth/usd': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.2, 0.5, 0.1, 0.2],
        0.01,
    ],
    'dot/usd': [
        ['bitfinexSpot', 'krakenSpot', 'hitbtcSpot'],
        [0.3, 0.6, 0.05],
        0.01,
    ],
    'wbtc/usd': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.25, 0.25, 0.25, 0.25],
        0.01,
    ],

    'btc/usd(wt)': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.2486, 0.4498, 0.0461, 0.2022],
        0.01,
    ],
    'btc/usdt(dusd)': [
        ['huobiSpot', 'binanceSpot', 'poloSpot'],
        [0.55, 0.35, 0.1],
        0.01,
    ],
    'btc/usd(wpt)': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.2486, 0.4498, 0.0461, 0.2022],
        0.01,
    ],
    'btc/usd(whc)': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.2486, 0.4498, 0.0461, 0.2022],
        0.01,
    ],
    'eth/usd(wt)': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.2,0.5,0.1,0.2],
        0.01,
    ],
    'eth/usd(wpt)': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.2,0.5,0.1,0.2],
        0.01,
    ],
    'eth/usd(whc)': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.2,0.5,0.1,0.2],
        0.01,
    ],
    'eth/usdt(dusd)': [
        ['huobiSpot', 'binanceSpot', 'poloSpot'],
        [0.55, 0.35, 0.1],
        0.01,
    ],
    'btc/usd(gia)': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.2486, 0.4498, 0.0461, 0.2022],
        0.01,
    ],
    'eth/usd(gia)': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.2,0.5,0.1,0.2],
        0.01,
    ],
    'btc/usd(zs)': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.2486, 0.4498, 0.0461, 0.2022],
        0.01,
    ],
    'btc/usd(aib)': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.2486, 0.4498, 0.0461, 0.2022],
        0.01,
    ],
    'eth/usd(aib)': [
        ['bitstampSpot', 'coinbaseSpot', 'geminiSpot', 'krakenSpot'],
        [0.2,0.5,0.1,0.2],
        0.01,
    ],
    'bico/usdt': [
        ['huobiSpot', 'okexSpot', 'gateioSpot', 'kucoinSpot'],
        [0.25, 0.25, 0.25, 0.25],
        0.01,
    ],
    'btc/usdt(lego)': [
        ['huobiSpot', 'binanceSpot', 'poloSpot'],
        [0.55, 0.35, 0.1],
        0.01,
    ],
    'btc/usdt(bobc)': [
        ['huobiSpot', 'binanceSpot', 'poloSpot'],
        [0.55, 0.35, 0.1],
        0.01,
    ],

}
