pushServerDict = {
    '9999999': [  # btc/susd
        ['wbfUsdtSwap', 'btc/susd'],
        ['huobiSpot', 'btc/usdt'],
        ['binanceSpot', 'btc/usdt'],
        # ['okexSpot', 'btc/usdt'],
        ['poloSpot', 'btc/usdt'],
        ['binanceUsdtSwap', 'btc/usdt'],
    ],
    '9100000': [  # btc/usdt
        ['wbfUsdtSwap', 'btc/usdt'],
        ['huobiSpot', 'btc/usdt'],
        ['binanceSpot', 'btc/usdt'],
        # ['okexSpot', 'btc/usdt'],
        ['poloSpot', 'btc/usdt'],
        ['binanceUsdtSwap', 'btc/usdt'],
        ['bullSpot', 'btc/usdt'],
        # ['huobiSpot1', 'btc/usdt'],
    ],
    '9100001': [  # eth/usdt
        #['wbfUsdtSwap', 'eth/usdt'],
        ['huobiSpot', 'eth/usdt'],
        ['binanceSpot', 'eth/usdt'],
        ['binanceUsdtSwap', 'eth/usdt'],
        ['okexSpot', 'eth/usdt'],
        ['poloSpot', 'eth/usdt'],
        ['binanceUsdtSwap', 'eth/usdt'],
        #['bullSpot', 'eth/usdt'],
        ['coinStoreUsdtSwap', 'eth/usdt'],
    ],
    '9100002': [  # eos/usdt
        ['wbfUsdtSwap', 'eos/usdt'],
        ['huobiSpot', 'eos/usdt'],
        ['binanceSpot', 'eos/usdt'],
        # ['okexSpot', 'eos/usdt'],
        ['hitbtcSpot', 'eos/usdt'],
        ['binanceUsdtSwap', 'eos/usdt'],
    ],
    '9100003': [  # comp/usdt
        ['wbfUsdtSwap', 'comp/usdt'],
        ['binanceSpot', 'comp/usdt'],
        ['mxcSpot', 'comp/usdt'],
        # ['okexSpot', 'comp/usdt'],
        ['hitbtcSpot', 'comp/usdt'],
        ['binanceUsdtSwap', 'comp/usdt'],
    ],
    '9100004': [  # atom/usdt
        ['wbfUsdtSwap', 'atom/usdt'],
        ['huobiSpot', 'atom/usdt'],
        ['binanceSpot', 'atom/usdt'],
        # ['okexSpot', 'atom/usdt'],
        ['poloSpot', 'atom/usdt'],
        ['binanceUsdtSwap', 'atom/usdt'],
    ],
    '9100005': [  # xrp/usdt
        ['wbfUsdtSwap', 'xrp/usdt'],
        ['huobiSpot', 'xrp/usdt'],
        ['binanceSpot', 'xrp/usdt'],
        # ['okexSpot', 'xrp/usdt'],
        ['mxcSpot', 'xrp/usdt'],
        ['binanceUsdtSwap', 'xrp/usdt'],
    ],
    '9100006': [  # ltc/usdt
        ['wbfUsdtSwap', 'ltc/usdt'],
        ['huobiSpot', 'ltc/usdt'],
        ['binanceSpot', 'ltc/usdt'],
        # ['okexSpot', 'ltc/usdt'],
        ['hitbtcSpot', 'ltc/usdt'],
        ['binanceUsdtSwap', 'ltc/usdt'],
        ['bullSpot', 'ltc/usdt']
    ],
    '9100007': [  # bch/usdt
        ['wbfUsdtSwap', 'bch/usdt'],
        ['huobiSpot', 'bch/usdt'],
        ['binanceSpot', 'bch/usdt'],
        # ['okexSpot', 'bch/usdt'],
        ['hitbtcSpot', 'bch/usdt'],
        ['binanceUsdtSwap', 'bch/usdt']
    ],
    '9100008': [  # bsv/usdt
        ['wbfUsdtSwap', 'bsv/usdt'],
        ['huobiSpot', 'bsv/usdt'],
        # ['binanceSpot', 'bsv/usdt'],
        # ['okexSpot', 'bsv/usdt'],
        ['hitbtcSpot', 'bsv/usdt'],
        ['binanceUsdtSwap', 'bsv/usdt'],
    ],
    '9100009': [  # etc/usdt
        ['wbfUsdtSwap', 'etc/usdt'],
        ['huobiSpot', 'etc/usdt'],
        ['binanceSpot', 'etc/usdt'],
        # ['okexSpot', 'etc/usdt'],
        ['hitbtcSpot', 'etc/usdt'],
        ['binanceUsdtSwap', 'etc/usdt'],
    ],
    '9100010': [  # trx/usdt
        ['wbfUsdtSwap', 'trx/usdt'],
        ['huobiSpot', 'trx/usdt'],
        ['binanceSpot', 'trx/usdt'],
        # ['okexSpot', 'trx/usdt'],
        ['hitbtcSpot', 'trx/usdt'],
        ['binanceUsdtSwap', 'trx/usdt'],
        ['bullSpot', 'trx/usdt']
    ],
    '9100011': [  # dot/usdt
        ['wbfUsdtSwap', 'dot/usdt'],
        ['huobiSpot', 'dot/usdt'],
        ['binanceSpot', 'dot/usdt'],
        # ['okexSpot', 'dot/usdt'],
        ['poloSpot', 'dot/usdt'],
        ['binanceUsdtSwap', 'dot/usdt'],
    ],
    '9100012': [  # link/usdt
        ['wbfUsdtSwap', 'link/usdt'],
        ['huobiSpot', 'link/usdt'],
        ['binanceSpot', 'link/usdt'],
        # ['okexSpot', 'link/usdt'],
        # ['poloSpot', 'link/usdt'],
        ['binanceUsdtSwap', 'link/usdt'],
    ],
    '9100013': [  # ada/usdt
        ['wbfUsdtSwap', 'ada/usdt'],
        ['huobiSpot', 'ada/usdt'],
        ['binanceSpot', 'ada/usdt'],
        # ['okexSpot', 'ada/usdt'],
        ['hitbtcSpot', 'ada/usdt'],
        ['binanceUsdtSwap', 'ada/usdt'],
    ],
    '9100014': [  # mkr/usdt
        ['wbfUsdtSwap', 'mkr/usdt'],
        ['huobiSpot', 'mkr/usdt'],
        ['binanceSpot', 'mkr/usdt'],
        # ['okexSpot', 'mkr/usdt'],
        ['kucoinSpot', 'mkr/usdt'],
        ['binanceUsdtSwap', 'mkr/usdt'],
    ],
    '9100015': [  # sushi/usdt
        ['wbfUsdtSwap', 'sushi/usdt'],
        ['huobiSpot', 'sushi/usdt'],
        ['binanceSpot', 'sushi/usdt'],
        # ['okexSpot', 'sushi/usdt'],
        ['gateioSpot', 'sushi/usdt'],
        ['binanceUsdtSwap', 'sushi/usdt'],
    ],
    '9100016': [  # uni/usdt
        ['wbfUsdtSwap', 'uni/usdt'],
        ['huobiSpot', 'uni/usdt'],
        ['binanceSpot', 'uni/usdt'],
        # ['okexSpot', 'uni/usdt'],
        ['gateioSpot', 'uni/usdt'],
        ['binanceUsdtSwap', 'uni/usdt'],
    ],
    '9100018': [  # fil/usdt
        ['wbfUsdtSwap', 'fil/usdt'],
        ['huobiSpot', 'fil/usdt'],
        ['binanceSpot', 'fil/usdt'],
        # ['okexSpot', 'fil/usdt'],
        ['gateioSpot', 'fil/usdt'],
        ['binanceUsdtSwap', 'fil/usdt'],
    ],
    '9100020': [  # grt/usdt
        ['wbfUsdtSwap', 'grt/usdt'],
        ['binanceUsdtSwap', 'grt/usdt'],
        ['gateioSpot', 'grt/usdt'],
        ['huobiSpot', 'grt/usdt'],
        ['binanceSpot', 'grt/usdt'],
        ['okexSpot', 'grt/usdt'],
    ],
    '9100022': [  # 1inch/usdt
        ['wbfUsdtSwap', '1inch/usdt'],
        ['binanceUsdtSwap', '1inch/usdt'],
        ['gateioSpot', '1inch/usdt'],
        ['huobiSpot', '1inch/usdt'],
        ['binanceSpot', '1inch/usdt'],
        ['okexSpot', '1inch/usdt'],
    ],
    '9100024': [  # dash/usdt
        ['wbfUsdtSwap', 'dash/usdt'],
        ['binanceUsdtSwap', 'dash/usdt'],
        ['hitbtcSpot', 'dash/usdt'],
        ['huobiSpot', 'dash/usdt'],
        ['binanceSpot', 'dash/usdt'],
        ['okexSpot', 'dash/usdt'],
    ],
    '9100026': [  # dot/usdt
        ['wbfUsdtSwap', 'dot/usdt'],
        ['binanceUsdtSwap', 'dot/usdt'],
        ['okexSpot', 'dot/usdt'],
        ['huobiSpot', 'dot/usdt'],
        ['binanceSpot', 'dot/usdt'],
        ['bitfinexSpot', 'dot/usdt'],
    ],
    '9100028': [  # aave/usdt
        ['wbfUsdtSwap', 'aave/usdt'],
        ['binanceUsdtSwap', 'aave/usdt'],
        ['okexSpot', 'aave/usdt'],
        ['huobiSpot', 'aave/usdt'],
        ['binanceSpot', 'aave/usdt'],
    ],
    '9100030': [  # yfi/usdt
        ['wbfUsdtSwap', 'yfi/usdt'],
        ['binanceUsdtSwap', 'yfi/usdt'],
        ['okexSpot', 'yfi/usdt'],
        ['huobiSpot', 'yfi/usdt'],
        ['binanceSpot', 'yfi/usdt'],
    ],
    '9100032': [  # doge/usdt
        ['wbfUsdtSwap', 'doge/usdt'],
        ['binanceUsdtSwap', 'doge/usdt'],
        ['okexSpot', 'doge/usdt'],
        ['huobiSpot', 'doge/usdt'],
        ['binanceSpot', 'doge/usdt'],
    ],
    '9100034': [  # xmr/usdt
        ['wbfUsdtSwap', 'xmr/usdt'],
        ['binanceUsdtSwap', 'xmr/usdt'],
        ['okexSpot', 'xmr/usdt'],
        ['huobiSpot', 'xmr/usdt'],
        ['binanceSpot', 'xmr/usdt'],
    ],
    '9100036': [  # avax/usdt
        ['wbfUsdtSwap', 'avax/usdt'],
        ['binanceUsdtSwap', 'avax/usdt'],
        ['okexSpot', 'avax/usdt'],
        ['huobiSpot', 'avax/usdt'],
        ['binanceSpot', 'avax/usdt'],
    ],
    '9100038': [  # snx/usdt
        ['wbfUsdtSwap', 'snx/usdt'],
        ['binanceUsdtSwap', 'snx/usdt'],
        ['okexSpot', 'snx/usdt'],
        ['huobiSpot', 'snx/usdt'],
        ['binanceSpot', 'snx/usdt'],
    ],
    '9100040': [  # ksm/usdt
        ['wbfUsdtSwap', 'ksm/usdt'],
        ['binanceUsdtSwap', 'ksm/usdt'],
        ['okexSpot', 'ksm/usdt'],
        ['huobiSpot', 'ksm/usdt'],
        ['binanceSpot', 'ksm/usdt'],
    ],
    '9100042': [  # zec/usdt
        ['wbfUsdtSwap', 'zec/usdt'],
        ['binanceUsdtSwap', 'zec/usdt'],
        ['okexSpot', 'zec/usdt'],
        ['huobiSpot', 'zec/usdt'],
        ['binanceSpot', 'zec/usdt'],
    ],
    '9100044': [  # zil/usdt
        ['wbfUsdtSwap', 'zil/usdt'],
        ['binanceUsdtSwap', 'zil/usdt'],
        ['okexSpot', 'zil/usdt'],
        ['huobiSpot', 'zil/usdt'],
        ['binanceSpot', 'zil/usdt'],
    ],
    '9100046': [  # waves/usdt
        ['wbfUsdtSwap', 'waves/usdt'],
        ['binanceUsdtSwap', 'waves/usdt'],
        ['okexSpot', 'waves/usdt'],
        ['huobiSpot', 'waves/usdt'],
        ['binanceSpot', 'waves/usdt'],
    ],
    '9100048': [  # zen/usdt
        ['wbfUsdtSwap', 'zen/usdt'],
        ['binanceUsdtSwap', 'zen/usdt'],
        ['okexSpot', 'zen/usdt'],
        ['huobiSpot', 'zen/usdt'],
        ['binanceSpot', 'zen/usdt'],
    ],
    '9100050': [  # ont/usdt
        ['wbfUsdtSwap', 'ont/usdt'],
        ['binanceUsdtSwap', 'ont/usdt'],
        ['okexSpot', 'ont/usdt'],
        ['huobiSpot', 'ont/usdt'],
        ['binanceSpot', 'ont/usdt'],
    ],
    '9100052': [  # torn/usdt
        ['wbfUsdtSwap', 'torn/usdt'],
        # ['binanceUsdtSwap', 'torn/usdt'],
        # ['okexSpot', 'torn/usdt'],
        ['okexSpot', 'torn/usdt'],
        # ['binanceSpot', 'torn/usdt'],
    ],
    '9100054': [  # mir/usdt
        ['wbfUsdtSwap', 'mir/usdt'],
        # ['binanceUsdtSwap', 'mir/usdt'],
        # ['okexSpot', 'mir/usdt'],
        ['okexSpot', 'mir/usdt'],
        # ['binanceSpot', 'mir/usdt'],
    ],
    '9100056': [  # mask/usdt
        ['wbfUsdtSwap', 'mask/usdt'],
        # ['binanceUsdtSwap', 'mask/usdt'],
        # ['okexSpot', 'mask/usdt'],
        ['huobiSpot', 'mask/usdt'],
        # ['binanceSpot', 'mask/usdt'],
    ],
    '9100080': [
        ['coinStoreUsdtSwap', 'sand/usdt'],
        ['huobiSpot', 'sand/usdt'],
        ['binanceSpot', 'sand/usdt'],
        ['okexSpot', 'sand/usdt'],
        #['kucoinSpot', 'sand/usdt'],
        ['binanceUsdtSwap', 'sand/usdt'],
        ['coinStoreUsdtSwap', 'bico/usdt'],
        ['huobiSpot', 'bico/usdt'],
        ['okexSpot', 'bico/usdt'],
        ['gateioSpot', 'bico/usdt'],
        ['coinStoreUsdtSwap', 'raca/usdt'],
        ['okexSpot', 'raca/usdt'],
        ['gateioSpot', 'raca/usdt'],
    ],
    '9100500': [  # bnb+ht/usdt
        ['wbfUsdtSwap', 'bnb+ht/usdt'],
        ['huobiSpot', 'ht/usdt'],
        ['binanceUsdtSwap', 'bnb/usdt'],
        ['gateioUsdtSwap', 'ht/usdt'],
        ['gateioUsdtSwap', 'bnb/usdt'],
    ],
    '9100501': [  # bnb-ht/usdt
        ['wbfUsdtSwap', 'bnb-ht/usdt'],
        ['huobiSpot', 'ht/usdt'],
        ['binanceUsdtSwap', 'bnb/usdt'],
        ['gateioUsdtSwap', 'ht/usdt'],
        ['gateioUsdtSwap', 'bnb/usdt'],
    ],

    '9190000': [
        ['wbfUsdtSwap', 'gray/usdt'],
        ['huobiSpot', 'btc/usdt'],
        ['huobiSpot', 'eth/usdt'],
        ['huobiSpot', 'etc/usdt'],
        ['huobiSpot', 'bch/usdt'],
        ['huobiSpot', 'ltc/usdt'],
        ['huobiSpot', 'zec/usdt'],
        ['huobiSpot', 'zen/usdt'],
        ['huobiSpot', 'xlm/usdt'],
        ['binanceSpot', 'btc/usdt'],
        ['binanceSpot', 'eth/usdt'],
        ['binanceSpot', 'etc/usdt'],
        ['binanceSpot', 'bch/usdt'],
        ['binanceSpot', 'ltc/usdt'],
        ['binanceSpot', 'zec/usdt'],
        ['binanceSpot', 'zen/usdt'],
        ['binanceSpot', 'xlm/usdt'],
    ],
    '9190001': [
        ['wbfUsdtSwap', 'pregray/usdt'],
        ['huobiSpot', 'aave/usdt'],
        ['huobiSpot', 'ada/usdt'],
        ['huobiSpot', 'atom/usdt'],
        ['huobiSpot', 'eos/usdt'],
        ['huobiSpot', 'xmr/usdt'],
        ['huobiSpot', 'dot/usdt'],
        ['huobiSpot', 'bat/usdt'],
        ['huobiSpot', 'link/usdt'],
        ['huobiSpot', 'mana/usdt'],
        ['huobiSpot', 'fil/usdt'],
        ['huobiSpot', 'xtz/usdt'],
        ['binanceSpot', 'aave/usdt'],
        ['binanceSpot', 'ada/usdt'],
        ['binanceSpot', 'atom/usdt'],
        ['binanceSpot', 'eos/usdt'],
        ['binanceSpot', 'xmr/usdt'],
        ['binanceSpot', 'dot/usdt'],
        ['binanceSpot', 'bat/usdt'],
        ['binanceSpot', 'link/usdt'],
        ['binanceSpot', 'mana/usdt'],
        ['binanceSpot', 'fil/usdt'],
        ['mxcSpot', 'lpt/usdt'],
        ['binanceSpot', 'xtz/usdt'],
    ],
    '9190002': [
        ['wbfUsdtSwap', 'polka/usdt'],
        # ['huobiSpot', 'dot/usdt'],
        # ['huobiSpot', 'ksm/usdt'],
        # ['huobiSpot', 'ocean/usdt'],
        # ['huobiSpot', 'pols/usdt'],
        # ['huobiSpot', 'akro/usdt'],
        # ['huobiSpot', 'mxc/usdt'],
        # ['huobiSpot', 'pha/usdt'],
        # ['huobiSpot', 'ankr/usdt'],
        # ['huobiSpot', 'celr/usdt'],
        # ['huobiSpot', 'dock/usdt'],
        # ['huobiSpot', 'cru/usdt'],
        # ['huobiSpot', 'ring/usdt'],
        # ['binanceSpot', 'dot/usdt'],
        # ['binanceSpot', 'ksm/usdt'],
        # ['binanceSpot', 'ocean/usdt'],
        # ['binanceSpot', 'pols/usdt'],
        # ['binanceSpot', 'akro/usdt'],
        # ['binanceSpot', 'mxc/usdt'],
        # ['binanceSpot', 'pha/usdt'],
        # ['binanceSpot', 'ankr/usdt'],
        # ['binanceSpot', 'celr/usdt'],
        # ['binanceSpot', 'dock/usdt'],
        # ['binanceSpot', 'cru/usdt'],
        # ['binanceSpot', 'ring/usdt'],
    ],
    '9190003': [
        ['wbfUsdtSwap', 'defi/usdt'],
        ['huobiSpot', 'uni/usdt'],
        ['huobiSpot', 'aave/usdt'],
        ['huobiSpot', 'snx/usdt'],
        ['huobiSpot', 'mkr/usdt'],
        ['huobiSpot', 'sushi/usdt'],
        ['huobiSpot', 'yfi/usdt'],
        ['huobiSpot', '1inch/usdt'],
        ['huobiSpot', 'comp/usdt'],
        ['binanceSpot', 'uni/usdt'],
        ['binanceSpot', 'aave/usdt'],
        ['binanceSpot', 'snx/usdt'],
        ['binanceSpot', 'mkr/usdt'],
        ['binanceSpot', 'sushi/usdt'],
        ['binanceSpot', 'yfi/usdt'],
        ['binanceSpot', '1inch/usdt'],
        ['binanceSpot', 'comp/usdt'],
    ],
    '9190004': [
        ['wbfUsdtSwap', 'nft/usdt'],
        # ['huobiSpot', 'enj/usdt'],
        ['huobiSpot', 'mana/usdt'],
        ['huobiSpot', 'sand/usdt'],
        ['huobiSpot', 'waxp/usdt'],
        # ['huobiSpot', 'cocos/usdt'],
        ['binanceSpot', 'enj/usdt'],
        ['binanceSpot', 'mana/usdt'],
        ['binanceSpot', 'sand/usdt'],
        # ['binanceSpot', 'waxp/usdt'],
        ['binanceSpot', 'cocos/usdt'],
        ['okexSpot', 'meme/usdt'],
        ['mxcSpot', 'ghst/usdt'],
    ],
    '9190005': [
        ['wbfUsdtSwap', 'heco/usdt'],
        ['huobiSpot', 'bags/usdt'],
        ['huobiSpot', 'mdx/usdt'],
        # ['binanceSpot', 'bags/usdt'],
        # ['binanceSpot', 'mdx/usdt'],
    ],
    '9190006': [
        ['wbfUsdtSwap', 'layer2/usdt'],
        ['huobiSpot', 'snx/usdt'],
        ['huobiSpot', 'lrc/usdt'],
        ['huobiSpot', 'near/usdt'],
        ['huobiSpot', 'omg/usdt'],
        ['huobiSpot', 'celr/usdt'],
        # ['huobiSpot', 'fun/usdt'],
        ['binanceSpot', 'snx/usdt'],
        ['binanceSpot', 'lrc/usdt'],
        ['binanceSpot', 'near/usdt'],
        ['binanceSpot', 'omg/usdt'],
        ['binanceSpot', 'celr/usdt'],
        ['binanceSpot', 'fun/usdt'],
    ],

    '9300001': [  # btc/usd(wt)
        ['wbfCoins', 'btc/usd(wt)'],
        ['bitstampSpot', 'btc/usd'],
        ['coinbaseSpot', 'btc/usd'],
        ['geminiSpot', 'btc/usd'],
        ['krakenSpot', 'btc/usd'],
    ],
    '9300002': [  # eth/usd(wt)
        ['wbfCoins', 'eth/usd(wt)'],
        ['bitstampSpot', 'eth/usd'],
        ['coinbaseSpot', 'eth/usd'],
        ['geminiSpot', 'eth/usd'],
        ['krakenSpot', 'eth/usd'],
    ],
    '9300003': [  # btc/usdt(dusd)
        ['wbfCoins', 'btc/usdt(dusd)'],
        ['huobiSpot', 'btc/usdt'],
        ['binanceSpot', 'btc/usdt'],
        # ['okexSpot', 'btc/usdt'],
        ['poloSpot', 'btc/usdt'],
    ],
    '9300004': [  # eth/usdt(dusd)
        ['wbfCoins', 'eth/usdt(dusd)'],
        ['huobiSpot', 'eth/usdt'],
        ['binanceSpot', 'eth/usdt'],
        # ['okexSpot', 'eth/usdt'],
        ['poloSpot', 'eth/usdt'],
    ],
    '9300005': [  # btc/usd(wpt)
        ['wbfCoins', 'btc/usd(wpt)'],
        ['bitstampSpot', 'btc/usd'],
        ['coinbaseSpot', 'btc/usd'],
        ['geminiSpot', 'btc/usd'],
        ['krakenSpot', 'btc/usd'],
    ],
    '9300007': [  # btc/usd(whc)
        ['wbfCoins', 'btc/usd(whc)'],
        ['bitstampSpot', 'btc/usd'],
        ['coinbaseSpot', 'btc/usd'],
        ['geminiSpot', 'btc/usd'],
        ['krakenSpot', 'btc/usd'],
    ],
    '9300008': [  # eth/usd(wpt)
        ['wbfCoins', 'eth/usd(wpt)'],
        ['bitstampSpot', 'eth/usd'],
        ['coinbaseSpot', 'eth/usd'],
        ['geminiSpot', 'eth/usd'],
        ['krakenSpot', 'eth/usd'],
    ],
    '9300009': [  # eth/usd(whc)
        ['wbfCoins', 'eth/usd(whc)'],
        ['bitstampSpot', 'eth/usd'],
        ['coinbaseSpot', 'eth/usd'],
        ['geminiSpot', 'eth/usd'],
        ['krakenSpot', 'eth/usd'],
    ],
    '9300010': [  # btc/usd(gia)
        ['wbfCoins', 'btc/usd(gia)'],
        ['bitstampSpot', 'btc/usd'],
        ['coinbaseSpot', 'btc/usd'],
        ['geminiSpot', 'btc/usd'],
        ['krakenSpot', 'btc/usd'],
    ],
    '9300011': [  # eth/usd(gia)
        ['wbfCoins', 'eth/usd(gia)'],
        ['bitstampSpot', 'eth/usd'],
        ['coinbaseSpot', 'eth/usd'],
        ['geminiSpot', 'eth/usd'],
        ['krakenSpot', 'eth/usd'],
    ],
    '9300012': [  # btc/usd(zs)
        ['wbfCoins', 'btc/usd(zs)'],
        ['bitstampSpot', 'btc/usd'],
        ['coinbaseSpot', 'btc/usd'],
        ['geminiSpot', 'btc/usd'],
        ['krakenSpot', 'btc/usd'],
    ],
    '9300013': [  # btc/usd(aib)
        ['wbfCoins', 'btc/usd(aib)'],
        ['bitstampSpot', 'btc/usd'],
        ['coinbaseSpot', 'btc/usd'],
        ['geminiSpot', 'btc/usd'],
        ['krakenSpot', 'btc/usd'],
    ],
    '9300014': [  # eth/usd(aib)
        ['wbfCoins', 'eth/usd(aib)'],
        ['bitstampSpot', 'eth/usd'],
        ['coinbaseSpot', 'eth/usd'],
        ['geminiSpot', 'eth/usd'],
        ['krakenSpot', 'eth/usd'],
    ],

    '9200001': [  # btc/usd
        ['wbfCoinSwap', 'btc/usd'],
        ['bitstampSpot', 'btc/usd'],
        ['coinbaseSpot', 'btc/usd'],
        ['geminiSpot', 'btc/usd'],
        ['krakenSpot', 'btc/usd'],
        ['binanceCoinSwap', 'btc/usd'],
    ],
    '9200002': [  # eth/usd
        ['wbfCoinSwap', 'eth/usd'],
        ['bitstampSpot', 'eth/usd'],
        ['coinbaseSpot', 'eth/usd'],
        ['geminiSpot', 'eth/usd'],
        ['krakenSpot', 'eth/usd'],
        ['binanceCoinSwap', 'eth/usd'],
    ],
    '9200003': [  # dot/usd
        ['wbfCoinSwap', 'dot/usd'],
        ['bitfinexSpot', 'dot/usd'],
        ['krakenSpot', 'dot/usd'],
        ['hitbtcSpot', 'dot/usd'],
        ['binanceCoinSwap', 'dot/usd']
    ],
    '9200004': [  # wbtc/usd
        ['wbfCoinSwap', 'wbtc/usd'],
        ['bitstampSpot', 'btc/usd'],
        ['coinbaseSpot', 'btc/usd'],
        ['geminiSpot', 'btc/usd'],
        ['krakenSpot', 'btc/usd'],
    ],
    '9200006': [  # uni/usd
        ['wbfCoinSwap', 'uni/usd'],
        ['huobiCoinSwap', 'uni/usd'],
    ],
    '9200008': [  # ltc/usd
        ['wbfCoinSwap', 'ltc/usd'],
        ['huobiCoinSwap', 'ltc/usd'],
    ],
    '9200010': [  # eos/usd
        ['wbfCoinSwap', 'eos/usd'],
        ['huobiCoinSwap', 'eos/usd'],
    ],
    '9200012': [  # xrp/usd
        ['wbfCoinSwap', 'xrp/usd'],
        ['huobiCoinSwap', 'xrp/usd'],
    ],
    '9200014': [  # trx/usd
        ['wbfCoinSwap', 'trx/usd'],
        ['huobiCoinSwap', 'trx/usd'],
    ],
    '9200016': [  # ada/usd
        ['wbfCoinSwap', 'ada/usd'],
        ['huobiCoinSwap', 'ada/usd'],
    ],
    '9200018': [  # bch/usd
        ['wbfCoinSwap', 'bch/usd'],
        ['huobiCoinSwap', 'bch/usd'],
    ],

    '9500001': [
        ['binanceUsdtSwap', 'dot/usdt'],
        ['binanceSpot', 'dot/usdt'],
    ],
    '9500002': [
        ['binanceUsdtSwap', 'ksm/usdt'],
        ['binanceSpot', 'ksm/usdt'],
    ],

    '9700000': [['coinStoreSpot', 'btc/usdt'], ['binanceUsdtSwap', 'btc/usdt'], ['binanceSpot', 'btc/usdt']],
    '9700001': [['coinStoreSpot', 'eth/usdt'], ['binanceUsdtSwap', 'eth/usdt'], ['binanceSpot', 'eth/usdt']],
    '9700002': [['coinStoreSpot', 'trx/usdt'], ['binanceUsdtSwap', 'trx/usdt'], ['binanceSpot', 'trx/usdt'],
                ['coinStoreSpot', 'uni/usdt'], ['binanceUsdtSwap', 'uni/usdt'], ['binanceSpot', 'uni/usdt'],
                ['coinStoreSpot', 'sushi/usdt'], ['binanceUsdtSwap', 'sushi/usdt'], ['binanceSpot', 'sushi/usdt'],
                ['coinStoreSpot', 'doge/usdt'], ['binanceUsdtSwap', 'doge/usdt'], ['binanceSpot', 'doge/usdt'],
                ['coinStoreSpot', '1inch/usdt'], ['binanceUsdtSwap', '1inch/usdt'], ['binanceSpot', '1inch/usdt']],
    '9700003': [['coinStoreSpot', 'lrc/usdt'], ['binanceUsdtSwap', 'lrc/usdt'], ['binanceSpot', 'lrc/usdt'],
                ['coinStoreSpot', 'grt/usdt'], ['binanceUsdtSwap', 'grt/usdt'], ['binanceSpot', 'grt/usdt'],
                #['coinStoreSpot', 'ocean/usdt'], ['binanceUsdtSwap', 'ocean/usdt'], ['binanceSpot', 'ocean/usdt'],
                ['coinStoreSpot', 'mana/usdt'], ['binanceUsdtSwap', 'mana/usdt'], ['binanceSpot', 'mana/usdt'],
                ['coinStoreSpot', 'rsr/usdt'], ['binanceUsdtSwap', 'rsr/usdt'], ['binanceSpot', 'rsr/usdt']],
    '9700004': [['coinStoreSpot', 'matic/usdt'], ['binanceUsdtSwap', 'matic/usdt'], ['binanceSpot', 'matic/usdt'],
                ['coinStoreSpot', 'chz/usdt'], ['binanceUsdtSwap', 'chz/usdt'], ['binanceSpot', 'chz/usdt'],
                ['coinStoreSpot', 'xrp/usdt'], ['binanceUsdtSwap', 'xrp/usdt'], ['binanceSpot', 'xrp/usdt'],
                ['coinStoreSpot', 'ada/usdt'], ['binanceUsdtSwap', 'ada/usdt'], ['binanceSpot', 'ada/usdt'],
                ['coinStoreSpot', 'gmt/usdt'], ['binanceUsdtSwap', 'gmt/usdt'], ['binanceSpot', 'gmt/usdt'],
                ['coinStoreSpot', 'gal/usdt'], ['binanceSpot', 'gal/usdt'],['binanceUsdtSwap', 'gal/usdt']
                ],
    '9700005': [
                ],
    '9700006': [['coinStoreSpot', 'dydx/usdt'], ['binanceUsdtSwap', 'dydx/usdt'], ['binanceSpot', 'dydx/usdt'],
                ['coinStoreSpot', 'chr/usdt'], ['binanceUsdtSwap', 'chr/usdt'], ['binanceSpot', 'chr/usdt'],
                ['coinStoreSpot', 'dot/usdt'], ['binanceUsdtSwap', 'dot/usdt'], ['binanceSpot', 'dot/usdt'],
                ['coinStoreSpot', 'reef/usdt'], ['binanceUsdtSwap', 'reef/usdt'], ['binanceSpot', 'reef/usdt'],
                ['coinStoreSpot', 'ftm/usdt'], ['binanceUsdtSwap', 'ftm/usdt'], ['binanceSpot', 'ftm/usdt'],
                ['coinStoreSpot', 'gala/usdt'], ['binanceUsdtSwap', 'gala/usdt'], ['binanceSpot', 'gala/usdt'],
                ['coinStoreSpot', 'sand/usdt'], ['binanceUsdtSwap', 'sand/usdt'], ['binanceSpot', 'sand/usdt'],
                ['coinStoreSpot', 'axs/usdt'], ['binanceUsdtSwap', 'axs/usdt'], ['binanceSpot', 'axs/usdt'],
                ['coinStoreSpot', 'c98/usdt'], ['binanceUsdtSwap', 'c98/usdt'], ['binanceSpot', 'c98/usdt']
                ],
    '9700007': [],
    '9700008': [ ['coinStoreSpot', 'agld/usdt'],['binanceSpot', 'agld/usdt'],
                 ['coinStoreSpot', 'lpt/usdt'], ['binanceSpot', 'lpt/usdt'],
                 ['coinStoreSpot', 'cake/usdt'], ['binanceSpot', 'cake/usdt'],
                 ['coinStoreSpot', 'shib/usdt'], ['binanceSpot', 'shib/usdt'], ['binanceUsdtSwap', '1000shib/usdt']],
    '9700009': [['coinStoreSpot', 'bico/usdt'], ['okexSpot', 'bico/usdt'], ['coinStoreSpot', 'raca/usdt'], ['binanceSpot', 'bico/usdt'],
                ['okexSpot', 'raca/usdt'], ['coinStoreSpot', 'people/usdt'], ['okexSpot', 'people/usdt'],
                ['coinStoreSpot', 'bat/usdt'], ['binanceSpot', 'bat/usdt'],['binanceUsdtSwap', 'bat/usdt'],
                ['coinStoreSpot', 'usdc/usdt'], ['okexSpot', 'usdc/usdt'],
                ['coinStoreSpot', 'bnb/usdt'], ['binanceSpot', 'bnb/usdt'],['binanceUsdtSwap', 'bnb/usdt'],
               ],
    '9700010': [
                # ['okexSpot', 'akita/usdt'], ['coinStoreSpot','akita/usdt'],
                ['coinStoreSpot', 'gal/usdt'], ['binanceSpot', 'gal/usdt'],['binanceUsdtSwap', 'gal/usdt'],
                ['coinStoreSpot', 'dogeking/usdt'], ['mxcSpot', 'dogeking/usdt'],
                ['coinStoreSpot', 'fort/usdt'], ['mxcSpot', 'fort/usdt'],
               ],
    '9700011': [['coinStoreSpot', 'alice/usdt'], ['binanceUsdtSwap', 'alice/usdt'], ['binanceSpot', 'alice/usdt'],
                ['coinStoreSpot', 'dash/usdt'], ['binanceUsdtSwap', 'dash/usdt'], ['binanceSpot', 'dash/usdt'],
                ['coinStoreSpot', 'fil/usdt'], ['binanceUsdtSwap', 'fil/usdt'], ['binanceSpot', 'fil/usdt'],
               ],
    '9700012': [['coinStoreSpot', 'crv/usdt'], ['binanceUsdtSwap', 'crv/usdt'],['binanceSpot', 'crv/usdt'],
                ['coinStoreSpot', 'mkr/usdt'], ['binanceUsdtSwap', 'mkr/usdt'],['binanceSpot', 'mkr/usdt'],
                #['coinStoreSpot', 'ftt/usdt'], ['binanceUsdtSwap', 'ftt/usdt'],['binanceSpot', 'ftt/usdt'],
                ['coinStoreSpot', 'enj/usdt'], ['binanceUsdtSwap', 'enj/usdt'],['binanceSpot', 'enj/usdt'],
                ['coinStoreSpot', 'link/usdt'], ['binanceUsdtSwap', 'link/usdt'],['binanceSpot', 'link/usdt'],
               ],
    '9700013': [['coinStoreSpot', 'ape/usdt'], ['binanceUsdtSwap', 'ape/usdt'],['binanceSpot', 'ape/usdt'],
                ['coinStoreSpot', 'snx/usdt'], ['binanceUsdtSwap', 'snx/usdt'],['binanceSpot', 'snx/usdt'],
                ['coinStoreSpot', 'algo/usdt'], ['binanceUsdtSwap', 'algo/usdt'],['binanceSpot', 'algo/usdt'],
                ['coinStoreSpot', 'aave/usdt'], ['binanceUsdtSwap', 'aave/usdt'],['binanceSpot', 'aave/usdt'],
                ['coinStoreSpot', 'avax/usdt'], ['binanceUsdtSwap', 'avax/usdt'],['binanceSpot', 'avax/usdt'],
               ],
    '9700014': [['coinStoreSpot', 'brise/usdt'], ['mxcSpot', 'brise/usdt'], 
               ],
    '9700015': [['coinStoreSpot', 'busd/usdt'], ['binanceSpot', 'busd/usdt']],

    '9800001': [['coinStoreSpot', 'mtrm/usdt']],
    '9800002': [['coinStoreSpot', 'town/usdt']],
    '9800003': [['coinStoreSpot', 'upp/usdt']],

    '9400001': [['coinStoreUsdtSwap', 'btc/usdt(dreams)'], ['binanceUsdtSwap', 'btc/usdt']],
    '9400002': [['coinStoreUsdtSwap', 'btc/usdt(bobc)'], ['binanceUsdtSwap', 'btc/usdt']]
    }

if __name__ == "__main__":
    # data = pushServerDict["9600002"]
    # new_data = []
    # # 下架币对
    # list_coin = ["LINK", "ZRX", "AAVE", "SNX", "COMP", "MKR", "YFI", "TRB", "OMG", "RLC", "CRV"
    #     , "SXP", "UNFI", "REN", "KSM", "SRM", "BAL"]
    # list_coin = [i.lower() + "/usdt" for i in list_coin]
    # print(len(data))
    # for num, i in enumerate(data):
    #     # print(num,i)
    #     if i[1] in list_coin:
    #         pass
    #         # print(num, i)
    #     else:
    #         new_data.append(i)
    # print(len(new_data))
    # new = ["axs", 'c98', 'gala', 'dydx', 'shib', 'slp', 'cake', 'ygg', 'agld']
    # new = [i.lower() + "/usdt" for i in new]
    # # new_data_1 = []
    # for i in new:
    #     new_data.append(['coinStoreSpot', i])
    #     new_data.append(['binanceUsdtSwap', i])
    #     new_data.append(['binanceSpot', i])
    #
    # print(len(new_data))
    # print(new_data)
    import os
    new_1 = ["axs", 'c98', 'gala', 'dydx']
    new_2 = ['shib', 'slp', 'cake', 'ygg', 'agld']
    for i in new_1:
        os.system(f"mkdir /usr/local/strategy/{i}usdt-coinStoreSpot")
        os.system(f"mkdir /usr/local/strategy/{i}usdt-coinStoreSpot/coinStorehedge")

    for i in new_2:
        os.system(f"mkdir /usr/local/strategy/{i}usdt-coinStoreSpot")
        os.system(f"mkdir /usr/local/strategy/{i}usdt-coinStoreSpot/coinStorehedgeSpot")
